[package]
name = "poreppacknif"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "poreppacknif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = { version = "0.34.0", features = ["nif_version_2_16"] }
sha2 = "0.10.8"
